require:
  - rubocop-rails

Rails:
  Enabled: true

AllCops:
  NewCops: enable
  DisplayCopNames: true
  SuggestExtensions: false
  Exclude:
    - 'bin/**/*'
    - 'config/**/*'
    - 'vendor/**/*'
    - 'Rakefile'
    - 'config.ru'
    - 'Gemfile'
    - 'db/schema.rb'

Style/FrozenStringLiteralComment:
  Enabled: true

Style/AsciiComments:
  Enabled: false

Style/Documentation:
  Enabled: false

# テストと Rake タスクの中でブロック行数を見ない
Metrics/BlockLength:
  Exclude:
    - 'lib/tasks/**/*'
    - 'spec/**/*'

Rails/I18nLocaleTexts:
  Enabled: false

Metrics/MethodLength:
  Enabled: false