version: "3.9"
services:
  db:
    image: postgres
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
  app:
    build: .
    tty: true
    stdin_open: true
    command: sh -c "rm -f tmp/pids/server.pid && bundle install && ./bin/dev"
    volumes:
      - .:/hayate
    ports:
      - "3000:3000"
    depends_on:
      - db
  worker:
    build: .
    tty: true
    stdin_open: true
    command: sh -c "bundle install && ./bin/jobs"
    volumes:
      - .:/hayate
    depends_on:
      - db