default: &default
  adapter: postgresql
  encoding: unicode
  host: db
  username: postgres
  password: password
  pool: 5

development:
  <<: *default
  database: hayate_development

test:
  <<: *default
  database: hayate_test

production:
  <<: *default
  host: <%= ENV["DATABASE_HOST"] %>
  database: postgres
  username: <%= ENV["DATABASE_USERNAME"] %>
  password: <%= ENV["DATABASE_PASSWORD"] %>