name: Bundle update every week

# on:
#   schedule:
#     - cron: '0 0 * * 0'

on: push

jobs:
  createPullRequest:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Get ruby version
        id: ruby
        run: echo "version=$(cat .ruby-version)" >> $GITHUB_OUTPUT

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ steps.ruby.outputs.version }}

      - name: Bundle update
        run: bundle update

      - name: Get current date
        id: date
        run: echo "date=$(date +'%Y-%m-%d')" >> $GITHUB_OUTPUT

      - name: Create pull request
        uses: peter-evans/create-pull-request@v6
        with:
          commit-message: Update gems
          title: Update gems at ${{ steps.date.outputs.date }}
          body: |
            This PR updates gems.
          branch: bundle-update-${{ steps.date.outputs.date }}
          base: main
          labels: dependencies
          reviewers: octocat
          assignees: octocat
