name: Run Rubocop
on: push

jobs:
  rubocop:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Ruby Env
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.3.5'
          bundler-cache: true

      - name: Show ruby version
        run: ruby -v

      - name: Run lint
        run: bundle exec rubocop
